### ISSUE TITLE
Error thrown when passing config_file.json as command line parameter

### ISSUE THREAD

**Issue by tinsami1** [MoneroOcean/meta-miner#1]
`root@Ubuntu1804MATEbeta:/home/xmr#  ./mm.js mm3333.json
>>> Meta Miner v0.5
module.js:549
    throw err;
    ^

Error: Cannot find module 'mm3333.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at load_config_file (/home/xmr/meta-miner/mm.js:586:16)
    at /home/xmr/meta-miner/mm.js:517:9
    at Array.forEach (<anonymous>)
    at parse_argv (/home/xmr/meta-miner/mm.js:512:25)
    at Object.<anonymous> (/home/xmr/meta-miner/mm.js:643:1)
    at Module._compile (module.js:652:30)
root@Ubuntu1804MATEbeta:/home/xmr#  ./mm.js mm.json
>>> Meta Miner v0.5
module.js:549
    throw err;
    ^

Error: Cannot find module 'mm.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at load_config_file (/home/xmr/meta-miner/mm.js:586:16)
    at /home/xmr/meta-miner/mm.js:517:9
    at Array.forEach (<anonymous>)
    at parse_argv (/home/xmr/meta-miner/mm.js:512:25)
    at Object.<anonymous> (/home/xmr/meta-miner/mm.js:643:1)
    at Module._compile (module.js:652:30)
root@Ubuntu1804MATEbeta:/home/xmr#  ls -hl mm*
-rw-r--r-- 1 root root 1.6K Aug 13 09:45 mm3333.json
lrwxrwxrwx 1 root root   16 Aug 13 09:31 mm.js -> meta-miner/mm.js
-rw-r--r-- 1 root root 1.6K Aug 13 09:41 mm.json`

**Comment by MoneroOcean** [comment]
Please try to use `./mm3333.json`

**Comment by MoneroOcean** [comment]
Also put a fix for that. Thanks for report!
